# Generated by Django 5.1.5 on 2026-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('taux_commission', models.DecimalField(decimal_places=2, default=2.0, help_text='Taux de commission en pourcentage (ex: 2.00 = 2%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
            },
        ),
    ]
