# Generated by Django 5.1.5 on 2026-02-21 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recouvrement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('montant', models.IntegerField()),
                ('taux_commission', models.DecimalField(decimal_places=4, max_digits=5)),
                ('commission', models.IntegerField()),
                ('methode_paiement', models.CharField(choices=[('MTN_MOMO', 'MTN MoMo'), ('ORANGE_MONEY', 'Orange Money'), ('ESPECES', 'Especes')], max_length=15)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REJETE', 'Rejete')], default='EN_ATTENTE', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to=settings.AUTH_USER_MODEL)),
                ('point_de_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recouvrements', to='pdv.pointdevente')),
            ],
            options={
                'db_table': 'recouvrements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneRecouvrement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('BOISSONS', 'Boissons'), ('ALIMENTATION', 'Alimentation'), ('HABILLEMENT', 'Habillement'), ('ELECTRONIQUE', 'Electronique'), ('AUTRE', 'Autre')], max_length=15)),
                ('prix_unitaire', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('sous_total', models.IntegerField()),
                ('recouvrement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='recouvrements.recouvrement')),
            ],
            options={
                'db_table': 'lignes_recouvrement',
            },
        ),
        migrations.AddIndex(
            model_name='recouvrement',
            index=models.Index(fields=['point_de_vente'], name='recouvremen_point_d_bde790_idx'),
        ),
        migrations.AddIndex(
            model_name='recouvrement',
            index=models.Index(fields=['agent'], name='recouvremen_agent_i_81bd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='recouvrement',
            index=models.Index(fields=['status'], name='recouvremen_status_c9f455_idx'),
        ),
        migrations.AddIndex(
            model_name='recouvrement',
            index=models.Index(fields=['methode_paiement'], name='recouvremen_methode_e015cd_idx'),
        ),
        migrations.AddIndex(
            model_name='recouvrement',
            index=models.Index(fields=['created_at'], name='recouvremen_created_78f5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='lignerecouvrement',
            index=models.Index(fields=['recouvrement'], name='lignes_reco_recouvr_9c03ee_idx'),
        ),
        migrations.AddIndex(
            model_name='lignerecouvrement',
            index=models.Index(fields=['categorie'], name='lignes_reco_categor_594295_idx'),
        ),
    ]
