# Generated by Django 5.1.5 on 2026-02-21 12:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(default='Abidjan', max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('proprietaire_nom', models.CharField(max_length=255)),
                ('proprietaire_telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numero de telephone doit etre au format ivoirien (ex: 0707070707).', regex='^0[1-9]\\d{8}$')])),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_de_vente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_de_vente',
                'indexes': [models.Index(fields=['agent'], name='points_de_v_agent_i_f070a3_idx'), models.Index(fields=['status'], name='points_de_v_status_d25e72_idx'), models.Index(fields=['commune'], name='points_de_v_commune_f6bd91_idx')],
            },
        ),
    ]
